clients:
  - nodeId: 1
    ip: 127.0.0.1
    port: 8001
  - nodeId: 2
    ip: 127.0.0.1
    port: 8002
  - nodeId: 3
    ip: 127.0.0.1
    port: 8003
  - nodeId: 4
    ip: 127.0.0.1
    port: 8004
  - nodeId: 5
    ip: 127.0.0.1
    port: 8005

